import React, { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createPortal } from 'react-dom';
import { EditorContent, useEditor } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import Placeholder from '@tiptap/extension-placeholder';
import './styles.css';
import './block-modal.css';
import './group-workspace.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
type Block = { id?: string; contentBlockId?: string | null; title: string; content: any; notes?: string | null };
type Report = { id: string; title: string; status: string; groupId?: string; blocks?: Block[]; group?: { name: string; members: { name: string; email: string }[] } };
type Dashboard = { reports: (Report & { group?: { name: string }; _count: { blocks: number } })[]; groups: { id: string; name: string; _count: { members: number } }[]; blocks: { id: string; title: string; category: string; content: any }[] };
const doc = (text = '') => ({ type: 'doc', content: text ? [{ type: 'paragraph', content: [{ type: 'text', text }] }] : [{ type: 'paragraph' }] });
async function request(path: string, token?: string, options: RequestInit = {}) { const r = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }); const data = await r.json(); if (!r.ok) throw new Error(data.error || 'Something went wrong'); return data; }

function RichEditor({ value, onChange, placeholder }: { value: any; onChange: (value: any) => void; placeholder: string }) {
  const editor = useEditor({ extensions: [StarterKit, Placeholder.configure({ placeholder })], content: value || doc(), onUpdate: ({ editor }) => onChange(editor.getJSON()) });
  useEffect(() => { if (editor && JSON.stringify(editor.getJSON()) !== JSON.stringify(value)) editor.commands.setContent(value || doc(), false); }, [editor, value]);
  if (!editor) return null;
  return <div className="editor"><div className="toolbar"><button onClick={() => editor.chain().focus().toggleBold().run()} className={editor.isActive('bold') ? 'active' : ''}>B</button><button onClick={() => editor.chain().focus().toggleBulletList().run()}>• List</button><button onClick={() => editor.chain().focus().toggleHeading({ level: 2 }).run()}>H2</button></div><EditorContent editor={editor} /></div>;
}

function Auth({ onAuth }: { onAuth: (token: string) => void }) {
  const [isLogin, setIsLogin] = useState(true), [error, setError] = useState('');
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); try { const data = await request(`/auth/${isLogin ? 'login' : 'register'}`, undefined, { method: 'POST', body: JSON.stringify({ name: f.get('name'), email: f.get('email'), password: f.get('password') }) }); localStorage.setItem('ld_token', data.token); onAuth(data.token); } catch (e) { setError((e as Error).message); } }
  return <main className="auth"><section><p className="eyebrow">LEADERSHIP DNA</p><h1>Build reports that move people forward.</h1><p>Turn your proven Leadership DNA content into thoughtful, personalized client reports.</p></section><form onSubmit={submit} className="card"><h2>{isLogin ? 'Welcome back' : 'Create your workspace'}</h2>{!isLogin && <label>Name<input required name="name" /></label>}<label>Email<input required type="email" name="email" defaultValue={isLogin ? 'demo@leadershipdna.com' : ''} /></label><label>Password<input required type="password" name="password" defaultValue={isLogin ? 'welcome123' : ''} /></label>{error && <p className="error">{error}</p>}<button className="primary">{isLogin ? 'Sign in' : 'Create account'}</button><button type="button" className="link" onClick={() => setIsLogin(!isLogin)}>{isLogin ? 'Need an account?' : 'Already have an account?'}</button><small>Demo: demo@leadershipdna.com / welcome123 (after seeding)</small></form></main>;
}

function App() {
  const [token, setToken] = useState(localStorage.getItem('ld_token') || ''), [data, setData] = useState<Dashboard | null>(null), [view, setView] = useState<'reports' | 'groups' | 'library' | 'editor'>('reports'), [report, setReport] = useState<Report | null>(null), [notice, setNotice] = useState('');
  const load = async () => { if (!token) return; try { setData(await request('/dashboard', token)); } catch { localStorage.removeItem('ld_token'); setToken(''); } };
  useEffect(() => { load(); }, [token]);
  useEffect(() => { const refresh = () => { load(); }; window.addEventListener('content-library:changed', refresh); return () => window.removeEventListener('content-library:changed', refresh); }, [token]);
  useEffect(() => { const addEmptyBlock = () => { if (report) setReport({ ...report, blocks: [...(report.blocks || []), { title: 'New content block', content: doc() }] }); }; window.addEventListener('report:add-empty-block', addEmptyBlock); return () => window.removeEventListener('report:add-empty-block', addEmptyBlock); }, [report]);
  useEffect(() => { const moveBlock = (event: Event) => { if (!report) return; const { index, direction } = (event as CustomEvent<{ index: number; direction: -1 | 1 }>).detail; const blocks = [...(report.blocks || [])], next = index + direction; if (next < 0 || next >= blocks.length) return; [blocks[index], blocks[next]] = [blocks[next], blocks[index]]; setReport({ ...report, blocks }); }; window.addEventListener('report:move-block', moveBlock); return () => window.removeEventListener('report:move-block', moveBlock); }, [report]);
  async function newReport() { const title = window.prompt('Report title', 'Leadership DNA Report'); if (!title) return; const r = await request('/reports', token, { method: 'POST', body: JSON.stringify({ title, groupId: data?.groups[0]?.id }) }); await openReport(r.id); }
  async function openReport(id: string) { setReport(await request(`/reports/${id}`, token)); setView('editor'); }
  useEffect(() => { const open = (event: Event) => { openReport((event as CustomEvent<string>).detail); }; window.addEventListener('report:open', open); return () => window.removeEventListener('report:open', open); }, [token]);
  async function saveReport() { if (!report) return; const updated = await request(`/reports/${report.id}`, token, { method: 'PUT', body: JSON.stringify({ title: report.title, blocks: report.blocks || [] }) }); setReport({ ...report, blocks: updated.blocks }); setNotice('Saved'); await load(); }
  function createBlock() { window.dispatchEvent(new Event('content-library:open-form')); }
  const nav = <aside><div className="brand">LD<span>•</span></div><button className={view === 'reports' ? 'selected' : ''} onClick={() => setView('reports')}>Reports</button><button className={view === 'groups' ? 'selected' : ''} onClick={() => setView('groups')}>Groups</button><button className={view === 'library' ? 'selected' : ''} onClick={() => setView('library')}>Content library</button>{view === 'library' && <button className="add-content-block" onClick={createBlock}>+ Add new content block</button>}<button className="logout" onClick={() => { localStorage.removeItem('ld_token'); setToken(''); }}>Sign out</button></aside>;
  if (!token) return <Auth onAuth={setToken} />; if (!data) return <p className="loading">Loading your workspace…</p>;
  if (view === 'editor' && report) return <div className="shell">{nav}<main className="workspace"><header><button className="link" onClick={() => { setView('reports'); load(); }}>← All reports</button><input className="title-input" value={report.title} onChange={e => setReport({ ...report, title: e.target.value })}/><div><button className="secondary" onClick={saveReport}>Save</button><button className="primary" onClick={async () => { try { const r = await request(`/reports/${report.id}/send`, token, { method: 'POST' }); setNotice(r.message); } catch (e) { setNotice((e as Error).message); } }}>Email group</button></div></header>{notice && <p className="notice">{notice}</p>}<div className="builder"><section className="paper"><p className="eyebrow">LEADERSHIP DNA REPORT</p>{(report.blocks || []).map((block, i) => <article className="report-block" key={`${block.title}-${i}`}><div className="block-head"><input value={block.title} onChange={e => { const blocks = [...(report.blocks || [])]; blocks[i] = { ...block, title: e.target.value }; setReport({ ...report, blocks }); }} /><button onClick={() => setReport({ ...report, blocks: report.blocks?.filter((_, index) => index !== i) })}>Remove</button></div><RichEditor value={block.content} placeholder="Write report content…" onChange={content => { const blocks = [...(report.blocks || [])]; blocks[i] = { ...block, content }; setReport({ ...report, blocks }); }} /><textarea placeholder="Private facilitator notes" value={block.notes || ''} onChange={e => { const blocks = [...(report.blocks || [])]; blocks[i] = { ...block, notes: e.target.value }; setReport({ ...report, blocks }); }} /></article>)}</section><section className="library-panel"><h3>Content library</h3><p>Choose a block to add it to this report.</p>{data.blocks.map(b => <button className="library-block" key={b.id} onClick={() => setReport({ ...report, blocks: [...(report.blocks || []), { contentBlockId: b.id, title: b.title, content: b.content }] })}><small>{b.category}</small>{b.title}<span>＋</span></button>)}</section></div></main></div>;
  return <div className="shell">{nav}<main className="workspace"><header><div><p className="eyebrow">WORKSPACE</p><h1>{view === 'reports' ? 'Your reports' : view === 'groups' ? 'Client groups' : 'Content library'}</h1></div>{view === 'reports' && <button className="primary" onClick={newReport}>+ New report</button>}</header>{view === 'reports' && <section className="grid">{data.reports.map(r => <button className="report-card" key={r.id} onClick={() => openReport(r.id)}><small>{r.status} · {r.group?.name || 'No group'}</small><h2>{r.title}</h2><p>{r._count.blocks} content blocks</p></button>)}{!data.reports.length && <div className="empty">No reports yet. Create your first one to begin.</div>}</section>}{view === 'groups' && <Groups token={token} groups={data.groups} reload={load} />}{view === 'library' && <section className="grid">{data.blocks.map(b => <article className="content-card" key={b.id}><small>{b.category}</small><h2>{b.title}</h2><p>Reusable report content</p></article>)}</section>}</main></div>;
}
function Groups({ token, groups, reload }: { token: string; groups: Dashboard['groups']; reload: () => Promise<void> }) { const [name, setName] = useState(''); const [members, setMembers] = useState([{ name: '', email: '' }]); async function submit(e: FormEvent) { e.preventDefault(); await request('/groups', token, { method: 'POST', body: JSON.stringify({ name, members: members.filter(m => m.name && m.email) }) }); setName(''); setMembers([{ name: '', email: '' }]); reload(); } return <div className="groups"><form className="card" onSubmit={submit}><h2>New client group</h2><label>Group name<input value={name} required onChange={e => setName(e.target.value)} placeholder="Executive team" /></label>{members.map((m, i) => <div className="member" key={i}><input required placeholder="Name" value={m.name} onChange={e => setMembers(members.map((x, n) => n === i ? { ...x, name: e.target.value } : x))}/><input required type="email" placeholder="Email" value={m.email} onChange={e => setMembers(members.map((x, n) => n === i ? { ...x, email: e.target.value } : x))}/></div>)}<button type="button" className="link" onClick={() => setMembers([...members, { name: '', email: '' }])}>+ Add person</button><button className="primary">Create group</button></form><section className="grid">{groups.map(g => <article className="content-card" key={g.id}><small>GROUP</small><h2>{g.name}</h2><p>{g._count.members} people</p></article>)}</section></div>; }
function ContentBlockModal() {
  const [open, setOpen] = useState(false), [id, setId] = useState<string | null>(null), [title, setTitle] = useState(''), [category, setCategory] = useState('Profile'), [content, setContent] = useState(doc()), [error, setError] = useState(''), [saving, setSaving] = useState(false);
  const close = () => { setOpen(false); setId(null); setError(''); };
  useEffect(() => { const show = () => { setId(null); setTitle(''); setCategory('Profile'); setContent(doc()); setOpen(true); }; window.addEventListener('content-library:open-form', show); return () => window.removeEventListener('content-library:open-form', show); }, []);
  useEffect(() => { const edit = async (event: MouseEvent) => { const card = (event.target as Element | null)?.closest('.content-card'); if (!card || card.querySelector('small')?.textContent === 'GROUP') return; const title = card.querySelector('h2')?.textContent; const dashboard = await request('/dashboard', localStorage.getItem('ld_token') || undefined); const block = dashboard.blocks.find((item: Dashboard['blocks'][number]) => item.title === title); if (block) { setId(block.id); setTitle(block.title); setCategory(block.category); setContent(block.content); setError(''); setOpen(true); } }; document.addEventListener('click', edit); return () => document.removeEventListener('click', edit); }, []);
  async function submit(e: FormEvent) { e.preventDefault(); setSaving(true); try { await request(id ? `/blocks/${id}` : '/blocks', localStorage.getItem('ld_token') || undefined, { method: id ? 'PUT' : 'POST', body: JSON.stringify({ title, category, content }) }); close(); window.dispatchEvent(new Event('content-library:changed')); } catch (e) { setError((e as Error).message); } finally { setSaving(false); } }
  const addButton = <button className="page-add-content-block primary" onClick={() => window.dispatchEvent(new Event('content-library:open-form'))}>+ Add new content block</button>;
  if (!open) return addButton;
  return <>{addButton}<div className="modal-backdrop" role="presentation"><form className="content-block-modal" onSubmit={submit}><header><div><p className="eyebrow">CONTENT LIBRARY</p><h2>{id ? 'Edit content block' : 'Add new content block'}</h2></div><button type="button" className="modal-close" onClick={close} aria-label="Close">×</button></header><label>Block title<input required autoFocus value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g. Communication Style" /></label><label>Category<input required value={category} onChange={e => setCategory(e.target.value)} placeholder="e.g. Profile" /></label><label>Reusable content<RichEditor value={content} onChange={setContent} placeholder="Write the reusable report content…" /></label>{error && <p className="error">{error}</p>}<footer><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={saving}>{saving ? 'Saving…' : id ? 'Save changes' : 'Save content block'}</button></footer></form></div></>;
}
function ReportEmptyBlockButton() {
  const [target, setTarget] = useState<Element | null>(null);
  useEffect(() => { const observer = new MutationObserver(() => setTarget(document.querySelector('.library-panel'))); observer.observe(document.body, { childList: true, subtree: true }); setTarget(document.querySelector('.library-panel')); return () => observer.disconnect(); }, []);
  return target ? createPortal(<button className="report-empty-block primary" onClick={() => window.dispatchEvent(new Event('report:add-empty-block'))}>+ Add empty block</button>, target) : null;
}
function ReportBlockReorderControls() {
  const [heads, setHeads] = useState<Element[]>([]);
  useEffect(() => { const sync = () => setHeads(Array.from(document.querySelectorAll('.report-block .block-head'))); const observer = new MutationObserver(sync); observer.observe(document.body, { childList: true, subtree: true }); sync(); return () => observer.disconnect(); }, []);
  return <>{heads.map((head, index) => createPortal(<span className="reorder-controls"><button type="button" aria-label="Move block up" disabled={index === 0} onClick={() => window.dispatchEvent(new CustomEvent('report:move-block', { detail: { index, direction: -1 } }))}>↑</button><button type="button" aria-label="Move block down" disabled={index === heads.length - 1} onClick={() => window.dispatchEvent(new CustomEvent('report:move-block', { detail: { index, direction: 1 } }))}>↓</button></span>, head, `reorder-${index}`))}</>;
}
type GroupDetail = { id: string; name: string; members: { id?: string; name: string; email: string }[]; reports: { id: string; title: string; status: string }[] };
function GroupWorkspace() {
  const [group, setGroup] = useState<GroupDetail | null>(null), [error, setError] = useState(''), [saving, setSaving] = useState(false), [reportTitle, setReportTitle] = useState('');
  useEffect(() => { const openGroup = async (event: MouseEvent) => { const card = (event.target as Element | null)?.closest('.content-card'); if (!card || card.querySelector('small')?.textContent !== 'GROUP') return; const name = card.querySelector('h2')?.textContent; const dashboard = await request('/dashboard', localStorage.getItem('ld_token') || undefined); const summary = dashboard.groups.find((item: Dashboard['groups'][number]) => item.name === name); if (summary) { setGroup(await request(`/groups/${summary.id}`, localStorage.getItem('ld_token') || undefined)); setError(''); } }; document.addEventListener('click', openGroup); return () => document.removeEventListener('click', openGroup); }, []);
  const updateMember = (index: number, field: 'name' | 'email', value: string) => group && setGroup({ ...group, members: group.members.map((member, i) => i === index ? { ...member, [field]: value } : member) });
  async function save(e: FormEvent) { e.preventDefault(); if (!group) return; setSaving(true); try { const updated = await request(`/groups/${group.id}`, localStorage.getItem('ld_token') || undefined, { method: 'PUT', body: JSON.stringify({ name: group.name, members: group.members.map(({ name, email }) => ({ name, email })) }) }); setGroup({ ...group, ...updated }); window.dispatchEvent(new Event('content-library:changed')); } catch (e) { setError((e as Error).message); } finally { setSaving(false); } }
  async function addReport() { if (!group || !reportTitle.trim()) return; try { const report = await request('/reports', localStorage.getItem('ld_token') || undefined, { method: 'POST', body: JSON.stringify({ title: reportTitle.trim(), groupId: group.id }) }); setGroup({ ...group, reports: [report, ...group.reports] }); setReportTitle(''); window.dispatchEvent(new Event('content-library:changed')); window.dispatchEvent(new CustomEvent('report:open', { detail: report.id })); setGroup(null); } catch (e) { setError((e as Error).message); } }
  if (!group) return null;
  return <div className="group-workspace"><main><header><div><button className="link" onClick={() => setGroup(null)}>← All groups</button><p className="eyebrow">CLIENT GROUP</p><input className="title-input" value={group.name} onChange={e => setGroup({ ...group, name: e.target.value })} /></div><button className="secondary" onClick={() => setGroup(null)}>Close</button></header><div className="group-detail-grid"><form className="card" onSubmit={save}><h2>Group members</h2><p>These recipients will receive reports sent to this group.</p>{group.members.map((member, i) => <div className="member-edit" key={member.id || i}><input required aria-label="Member name" value={member.name} onChange={e => updateMember(i, 'name', e.target.value)} /><input required type="email" aria-label="Member email" value={member.email} onChange={e => updateMember(i, 'email', e.target.value)} /><button type="button" onClick={() => setGroup({ ...group, members: group.members.filter((_, n) => n !== i) })}>Remove</button></div>)}<button type="button" className="link" onClick={() => setGroup({ ...group, members: [...group.members, { name: '', email: '' }] })}>+ Add member</button>{error && <p className="error">{error}</p>}<button className="primary" disabled={saving}>{saving ? 'Saving…' : 'Save group'}</button></form><section className="card report-for-group"><p className="eyebrow">REPORTS</p><h2>Create a group report</h2><p>A report created here is automatically attached to this group and can be emailed to everyone listed.</p><input value={reportTitle} onChange={e => setReportTitle(e.target.value)} placeholder="Report title" /><button className="primary" onClick={addReport}>+ Create report for group</button>{group.reports.length > 0 && <div className="group-report-list">{group.reports.map(report => <button key={report.id} onClick={() => { window.dispatchEvent(new CustomEvent('report:open', { detail: report.id })); setGroup(null); }}><small>{report.status}</small>{report.title}</button>)}</div>}</section></div></main></div>;
}
createRoot(document.getElementById('root')!).render(<><App /><ContentBlockModal /><ReportEmptyBlockButton /><ReportBlockReorderControls /><GroupWorkspace /></>);
